version: "3.8"

services:
  api:
    container_name: cloud-storage-engine
    build: ./
#    image: test:1
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  postgres:
    image: postgres:latest
    restart: always
    container_name: cloud-storage-database
#    ports:
#      - 5432:5432
    environment:
      - POSTGRES_USER=vova
      - POSTGRES_PASSWORD=123
    volumes:
      - database_volume:/postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "vova" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    container_name: cloud-storage-redis
#    ports:
#      - 6379:6379
#    volumes:
#TODO
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  database_volume:
  redis_volume:
