version: "3.8"

services:
  api:
    container_name: cloud-storage-engine
    build: ./
    environment:
      EMAIL: put here your email
      EMAIL_PASSWORD: put here app password for your email
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy


  postgres:
    image: postgres:latest
    restart: always
    container_name: cloud-storage-database
    environment:
      - POSTGRES_USER=vova
      - POSTGRES_PASSWORD=123
    volumes:
      - database_volume:/postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "vova" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    container_name: cloud-storage-redis
    volumes:
      - redis_volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  minio:
    image: minio/minio
    restart: always
    container_name: cloud-storage-s3
    volumes:
      - minio_volume:/data
    command: server /data
    healthcheck:
      test: [ "CMD", "mc", "alias", "set", "myminio", "http://localhost:9000", "minioadmin", "minioadmin" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  database_volume:
  redis_volume:
  minio_volume:
