spring:
  datasource:
    username: vova
    password: 123
#    url: jdbc:postgresql://postgres:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres # для локального запуска
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


jwt:
  access-secret-key: "super_secret_key_which_should_be_long"
  refresh-secret-key: "123avc"
  access-expiration-time: 3600000
  refresh-expiration-time: 3600000


#  @Value("${jwt.access-secret-key}")
#    private String ACCESS_SECRET_KEY;
#    @Value("${jwt.refresh-secret-key}")
#    private String REFRESH_SECRET_KEY;
#    @Value("${jwt.access-expiration-time}")
#    private long ACCESS_EXPIRATION_TIME; // in minutes
#    @Value("${jwt.refresh-expiration-time}")